/** Entries Actions Types */

export const ENTRIES_FETCHED = 'entries.ENTRIES_FETCHED';
export const ENTRIES_FETCHED_SUCCESS = 'entries.ENTRIES_FETCHED_SUCCESS';
export const ENTRIES_FETCHED_FAILURE = 'entries.ENTRIES_FETCHED_FAILURE';

export const ENTRIES_ADD = 'entries.ENTRIES_ADD';
export const ENTRIES_ADD_SUCCESS = 'entries.ENTRIES_ADD_SUCCESS';
export const ENTRIES_ADD_FAILURE = 'entries.ENTRIES_ADD_FAILURE';

export const ENTRIES_DELETE = 'entries.ENTRIES_DELETE';
export const ENTRIES_DELETE_SUCCESS = 'entries.ENTRIES_DELETE_SUCCESS';
export const ENTRIES_DELETE_FAILURE = 'entries.ENTRIES_DELETE_FAILURE';

export const ENTRIES_ADD_SNAPSHOT = 'entries.ENTRIES_ADD_SNAPSHOT';
export const ENTRIES_ADD_SNAPSHOT_SUCCESS = 'entries.ENTRIES_ADD_SNAPSHOT_SUCCESS';
export const ENTRIES_ADD_SNAPSHOT_FAILURE = 'entries.ENTRIES_ADD_SNAPSHOT_FAILURE';
