/** Workspaces Actions Types */

export const WORKSPACES_FETCHED = 'workspaces.WORKSPACES_FETCHED';
export const WORKSPACES_FETCHED_SUCCESS =
  'workspaces.WORKSPACES_FETCHED_SUCCESS';
export const WORKSPACES_FETCHED_FAILURE =
  'workspaces.WORKSPACES_FETCHED_FAILURE';

export const WORKSPACES_ADD = 'workspaces.WORKSPACES_ADD';
export const WORKSPACES_ADD_SUCCESS = 'workspaces.WORKSPACES_ADD_SUCCESS';
export const WORKSPACES_ADD_FAILURE = 'workspaces.WORKSPACES_ADD_FAILURE';

export const WORKSPACES_DELETE = 'workspaces.WORKSPACES_DELETE';
export const WORKSPACES_DELETE_SUCCESS = 'workspaces.WORKSPACES_DELETE_SUCCESS';
export const WORKSPACES_DELETE_FAILURE = 'workspaces.WORKSPACES_DELETE_FAILURE';
